### ISSUE TITLE
Configuration is awkward

### ISSUE THREAD

**Issue by mivade** [tbenthompson/cppimport#14]
This is a really great project and I am interested in using it during development of extension modules. I would however prefer to use the more traditional methods of building extensions for releases in a lot of cases. The examples of configuration shown in the README are awkward in the sense that they use raw mako templates in the .cpp files directly which would result in failed builds if compiled directly. Some possible solutions:

- Put the mako configuration in comments (I tested this and it works without issue)
- Explicitly note in the README that the above is acceptable
- Optionally take a keyword argument in `cppimport.imp` for configuration and bypass mako entirely

**Comment by tbenthompson** [comment]
I agree that it's a bit awkward, but it also achieves the goal I wanted: to have the configuration embeded the C/C++ code so that a package can be distributed just by sending someone the source files and having them cppimport those files. I'm not actually sure that goal is appropriate though. It feels like this package might be trying to do too many things -- instead of just simplifying the construction and importing of extensions, it's trying to also be a build system. 

Anyway, I really appreciate your thoughts and if you ever want to make some of those modifications, that'd be awesome.

Given the current situation, I think if you want the .cpp files to compile without processing the Mako templates, then using block comments is absolutely the right way to go. I've done that a couple times.
