### ISSUE TITLE
Submodule importing triggers recompile on each run

### ISSUE THREAD

**Issue by sjperkins** [tbenthompson/cppimport#18]
This occurs on python 2.7.12 and cppimport==17.7.24

I've created a little package to test submodule imports. The package `__init__.py` looks as follows:

```python
import cppimport

mod = cppimport.imp("testcppimport.qux.foobar")
plort = mod.qux.foobar.plort
```

Now if I invoke `plort` in multiple interpreter runs, `foobar.so` is recompiled, even though  it already exists.
```bash
python -c 'from testcppimport import plort; plort()'
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
Plort
python -c 'from testcppimport import plort; plort()'
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
Plort
```

Some debugging indicates that the call to [find_module](https://github.com/tbenthompson/cppimport/blob/98ab93726376830b61fc00aeef48b819b71a1852/cppimport/find.py#L66) fails with ImportError `No module named testcppimport.qux.foobar`. So the find fails, `foobar.so` is recompiled, loaded and `plort()` is invoked.

The test package is here [testcppimport.zip](https://github.com/tbenthompson/cppimport/files/1306397/testcppimport.zip)

**Comment by tbenthompson** [comment]
I've fixed this in the latest commit on the "stable" branch. I hadn't run into this because most users are on Python 3 and this bug only appears in 2.7, but it actually led it substantial simplification of the checksum design, so thanks! Could you just check that your example works now?

Another comment: the latest version returns the submodule specified rather than the root directory. So you're `__init__.py` will need to look like:
```
import cppimport

mod = cppimport.imp("testcppimport.qux.foobar")
plort = mod.plort
```

**Comment by sjperkins** [comment]
@tbenthompson Thanks for the quick turnaround, this fixes the issue (and makes getting the submodule easier too). Would you mind cutting a release?

**Comment by tbenthompson** [comment]
Yep. Done!

**Comment by sjperkins** [comment]
Thank you kindly :-)
