### ISSUE TITLE
What if the cpp source file require another library (shared or static) for linkage?

### ISSUE THREAD

**Issue by huntzhan** [tbenthompson/cppimport#6]
This situation is pretty common.

**Comment by tbenthompson** [comment]
Very common! The "stable" branch doesn't handle this at all. I'm working on some ideas on how to expand the scope of cppimport in the "master" branch.

**Comment by huntzhan** [comment]
Cool!

**Comment by francescortiz** [comment]
OpenERP 7 parses comments to acquire metadata from modules. You could use a similar strategy and parse comments in the imported C++ file.

**Comment by tbenthompson** [comment]
Thanks for the suggestion! I'm actually considering something very similar but a little heavier and essentially running every file through the mako templating engine and then extracting the configuration from the template's context. This is cool because it can be as simple as embedding some configuration, or can go further and import (python) modules that do whatever processing you please. What do you think about that?

**Comment by francescortiz** [comment]
I like the idea. It gives you dynamic code generation for free. Good work!
