### ISSUE TITLE
[Question] Can we supress cppimport error messages/warnings when buillding the bindings?

### ISSUE THREAD

**Issue by siv2r** [tbenthompson/cppimport#63]
As mentioned in the https://github.com/tbenthompson/cppimport/issues/60#issuecomment-905772320, I was able to get cppimport working for a sample project using the `cfg['include_dirs'].append(path)`

I tried to implement the same method in Bitcoin Core for building the python bindings. The changes can be found [here](https://github.com/siv2r/bitcoin/tree/test_chacha20). The bindings are built properly, and they are working.

The problem is there are some error messages related to cppimport's inner workings are shown when these bindings are built. The error message can be found [here](https://pastebin.ubuntu.com/p/PhnkYHw3Bf/). 

A [stackoverflow thread](https://stackoverflow.com/questions/47335519/attributeerror-pyximporter-object-has-no-attribute-find-spec-with-pandas-bi) that is somewhat similar to this issue.

**Comment by tbenthompson** [comment]
Hmm. So what's going on here, as far as I can tell, is that something is causing exceptions internal to the Python import mechanism to get logged/printed. The Python importing system uses exceptions in order to bounce between different library import options. 

Without a small reproduction, I'm not sure I can help much here. I hope things worked out for you!

**Comment by siv2r** [comment]
Thanks for looking into this :)
