### ISSUE TITLE
Build failure on Mac OS

### ISSUE THREAD

**Issue by AtsushiSakai** [tbenthompson/cppimport#9]
Hi.
Your cppimport is great!!

However, the sample code's build fails on Mac OS.

My environment is
Mac OS:10.11.5
clang: Apple LLVM version 7.3.0 (clang-703.0.31)

Error message as below 
> In file included from /Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/pybind11/pybind11.h:30:
In file included from /Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/pybind11/attr.h:13:
In file included from /Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/pybind11/cast.h:13:
In file included from /Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/pybind11/pytypes.h:12:
/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/pybind11/common.h:72:10: fatal error: 
      'unordered_set' file not found
#include <unordered_set>
         ^
1 error generated.
error: command '/usr/bin/clang' failed with exit status 1

Do you know how to fix it?

Atsushi

**Comment by tbenthompson** [comment]
Interesting. Can you run `cppimport.set_quiet(False)` before the import command and then paste the full output? 

Also, if you're interested, you could try the version that's available from the "master" branch instead of the "stable" branch. Just install with `python setup.py install` and follow the example from the new readme (it's changed a bit!)

**Comment by AtsushiSakai** [comment]
Thank you reply.

The full output is:
> Matching checksum for /Users/AtsushiSakai/Dropbox/Program/python/sandbox/cppimportsample/somecode.cpp --> not compiling
Traceback (most recent call last):
  File "sample.py", line 7, in <module>
    import somecode #This will pause for a moment to compile the module
ImportError: dlopen(/Users/AtsushiSakai/Dropbox/Program/python/sandbox/cppimportsample/somecode.so, 2): no suitable image found.  Did find:
	/Users/AtsushiSakai/Dropbox/Program/python/sandbox/cppimportsample/somecode.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
shell returned 1

　

I will try the master branch later.

**Comment by tbenthompson** [comment]
Hi, 
If you're still interested, could you delete the generated ".so" file: `rm somecode.so` and re-run the script, still with `set_quiet(False)`? Did you ever try the master branch?

**Comment by demoslam** [comment]
I encountered similar error on my macOS 10.12.1, and I'm using Anaconda compiled python.
I think the reason is the setuptools does not including the correct C++11 header files based the info from Anaconda python, check [stackoverflow](http://stackoverflow.com/questions/33738885/python-setuptools-not-including-c-standard-library-headers). 

I can successfully import the module by adding option to `extra_compile_args`.
